# Generated by Django 6.0.6 on 2026-07-26 12:30

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[apps.accounts.validators.validate_e164_phone]),
        ),
    ]
